{"name": "test_auth", "status": "failed", "statusDetails": {"message": "AssertionError: \u001b[31mFAILURE: \u001b[0massert 200 == 401\n +  where 200 = <Response [200]>.status_code\n\u001b[31mtest_api_negative.py\u001b[0m:32 in test_auth() -> with check:\n\u001b[31mtest_api_negative.py\u001b[0m:33 in test_auth -> assert response.status_code == 401\n\u001b[31mAssertionError: assert 200 == 401\n +  where 200 = <Response [200]>.status_code\n\u001b[0m\n\n------------------------------------------------------------\nFailed Checks: 1", "trace": "\u001b[31mFAILURE: \u001b[0massert 200 == 401\n +  where 200 = <Response [200]>.status_code\n\u001b[31mtest_api_negative.py\u001b[0m:32 in test_auth() -> with check:\n\u001b[31mtest_api_negative.py\u001b[0m:33 in test_auth -> assert response.status_code == 401\n\u001b[31mAssertionError: assert 200 == 401\n +  where 200 = <Response [200]>.status_code\n\u001b[0m\n\n------------------------------------------------------------\nFailed Checks: 1"}, "steps": [{"name": "Auth credentials", "status": "passed", "start": 1759920039831, "stop": 1759920039831}, {"name": "Sending wrong credentials in auth request", "status": "passed", "start": 1759920039831, "stop": 1759920040897}, {"name": "Assertions", "status": "passed", "start": 1759920040897, "stop": 1759920040996}], "start": 1759920039831, "stop": 1759920040997, "uuid": "13c470d8-731b-4aad-aaa1-61c2b32fe21f", "historyId": "24c0d482ebd7a720a54251c3464a992c", "testCaseId": "6895e023ee1a939cbb46c6f1c3819ae5", "fullName": "tests.test_api_negative#test_auth", "labels": [{"name": "story", "value": "Negative testing"}, {"name": "feature", "value": "CRUD operations"}, {"name": "epic", "value": "API Client"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_negative"}, {"name": "host", "value": "DESKTOP-H6JKBAG"}, {"name": "thread", "value": "11576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_negative"}]}